[package]
name = "rtt_rs2"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = { version = "0.2", default-features = false}
linked_list_allocator = "0.10"

[build-dependencies]
bindgen = "0.69"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"
codegen-units = 1
