[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build-dependencies]
bindgen = "0.71.1"

[lib]
name = "rustffi"
crate-type = ["staticlib"]
path = "src/lib.rs"
